// Revision 7: spoken dialogue plus SCRIPT collections and screen copy below.
// Edit the TEXT freely. Keep the key names (left side) unless you also change the code that uses them.
// Speaker prefixes such as "LO:" and "AGENT:" pick the portrait, so keep those at the start of the line.
const LINES = {
  core: {
    create_1: "Another beautiful day in this lovely apartment...",
    update_1: "Nothing out there but the hallway and disappointment.",
    action_1: "That escalated quickly. Yesterday I was yelling at my rent notice. Now I have a home-buying team.",
    action_2: "YOU HAVE GOT TO BE KIDDING ME.",
    action_3: "Nothing out there but the hallway and disappointment.",
    action_4: "Maybe later.",
    action_5: "Enough internet for one day.",
    action_6: "The full statement is saved. Enough internet for one day.",
    action_7: "AGENT: Look at you: one pen away from being a homeowner. I'm here if you have questions.",
    action_8: "CLOSING HOST: Take your time with the papers. Ask if anything differs from what you reviewed.",
    action_9: "LO: Glad you made it. Take your time reviewing the papers. I'm here if you have questions.",
    action_10: "DISCOUNT REALTY BONANZA: 'Why pay full price for advice?'",
    action_11: "...I think I'll keep looking.",
    action_12: "Nice car. Somebody around here spends a lot of time driving to showings.",
    action_13: "COUSIN DAVE: You found an agent? Fair. Show me the weirdest house.",
    action_14: "ME: Deal. But I'm keeping the advice from the actual agent.",
    action_15: "COUSIN DAVE: Discount Realty is still right here if you change your mind.",
    action_16: "Thanks, Dave. I've got an agent helping me.",
    travel_1: "Pay stubs, W-2, photo ID, and the entire bank statement.\nTime to search this place.",
  },
  apartment: {
    crash_1: "...I'm buying a house.",
    beginScene2_1: "I should check the computer and figure out how to buy a home.",
    finishOverload_1: "Dave lives with his mom.",
    finishOverload_2: "I have absolutely no idea what I'm doing.",
    finishOverload_3: "The internet is making this worse.",
    finishOverload_4: "I'm talking to an actual human.",
  },
  loan_office: {
    talkToOfficer_1: "LO: Welcome! What brings you in today?",
    talkToOfficer_2: "My rent went up. The internet made me panic.\nCan I actually buy a house?",
    talkToOfficer_3: "LO: Let's find out together. Every loan file starts with four basics.",
    talkToOfficer_4: "LO: Let me have my assistant bring the whiteboard over.",
    talkToOfficer_5: "LO: The whiteboard is a good place to start.",
    talkToOfficer_6: "LO: Your checklist is at the printer.",
    talkToOfficer_7: "LO: Once you have completed the checklist and found all the documents, bring them back to me.",
    talkToOfficer_8: "LO: Your letter is waiting at the printer.",
    talkToOfficer_9: "LO: Ask your agent about the inspection, then bring me the contract.",
    talkToOfficer_10: "LO: You found your agent! How are the showings going?",
    talkToOfficer_11: "LO: Check taxes and HOA dues with me before deciding on an offer.",
    talkToOfficer_12: "LO: You've got a starting point. Now find an agent to help with the home search.",
    collectPreapproval_1: "Preapproval letter in hand. Time to find a reputable agent who can explain things without 47 browser tabs.",
    beginQualificationReview_1: "LO: Good. Now let me review your documents against the budget we discussed.",
    siftQualificationPapers_1: "LO: Congratulations! You're preapproved to start your home search.",
    siftQualificationPapers_2: "ME: Cousin Dave knows a guy who helps buyers. What do you think?",
    siftQualificationPapers_3: "LO: A home is one of the biggest financial decisions you'll make.",
    siftQualificationPapers_4: "LO: Find a reputable agent who explains things and looks out for you.",
    siftQualificationPapers_5: "LO: I'll print your preapproval letter now.",
    handDocumentsToOfficer_1: "ME: I brought the pay stubs, W-2, photo ID, and every page of the bank statement.",
    handDocumentsToOfficer_2: "LO: Perfect. Let me spread these out and review them with you.",
    startFinancialReview_1: "LO: Let's look at your income, savings, and monthly payments together.",
    startFinancialReview_2: "LO: These documents give us a starting point. We'll verify the details as we go.",
    startFinancialReview_3: "LO: Taco emergency... premium dog hats... beans of the month?",
    startFinancialReview_4: "ME: Please tell me the dog hats aren't an automatic no.",
    startFinancialReview_5: "LO: They're a conversation starter. There's also a $4,000 deposit. Where did it come from?",
    startFinancialReview_6: "ME: My aunt sent it to help with the house.",
    startFinancialReview_7: "LO: We'll document that before counting it toward your funds. That wraps up our first review.",
    collectReviewedDocuments_1: "LO: Could you collect these documents for me, please?",
    collectReviewedDocuments_2: "ASSISTANT (offscreen): This many OnlyFans charges? He's already supporting a small neighborhood.",
    collectReviewedDocuments_3: "ME: ...You know these walls are very thin, right?",
    collectReviewedDocuments_4: "LO: Anyway. Let's talk about a comfortable monthly budget.",
    collectDocument_1: "That's the whole file. Back to the loan officer.",
    maybeShowStatementHint_1: "I should be able to get my bank statements from the internet.",
    deliverWhiteboard_1: "LO: Take a look at the whiteboard, then we'll make a plan.",
    deliverWhiteboard_2: "ASSISTANT: Here you go.",
    deliverWhiteboard_3: "LO: Take a look at the whiteboard, then we'll make a plan.",
    nextLoanPage_1: "LO: See? A starting point.\nThe printer has your document checklist.",
    printChecklist_1: "CHECKLIST: Pay stubs, W-2,\nfull bank statement, photo ID.",
    printChecklist_2: "LO: The entire bank statement, please. Every page.",
    printChecklist_3: "LO: Let's start at home. Bring what you find back to me.",
  },
  town: {
    startDaveDowntownIntro_1: "COUSIN DAVE: Hey! I know an agent who can help you. Discount Realty — right there.",
    startDaveDowntownIntro_2: "ME: Thanks, Dave. My loan officer suggested I find a reputable agent I can trust.",
  },
  realtor_office: {
    enterRealtorOffice_1: "AGENT: Hey! Welcome to Keller Williams. What brings you in?",
    enterRealtorOffice_2: "ME: My loan officer recommended a reputable agent for my home search.",
    enterRealtorOffice_3: "ME: I'd like to understand how you work with buyers.",
    enterRealtorOffice_4: "AGENT: Absolutely. Have a seat and we'll talk about what you're looking for.",
    seatBuyerAndAgent_1: "ME: I just got preapproved. I want help finding the right home and understanding the numbers.",
    seatBuyerAndAgent_2: "AGENT: Perfect. That's exactly what a buyer consultation is for. Let's narrow it down before we start driving all over town.",
    talkToRealtor_1: "AGENT: Grab the chair beside the table and we'll get started.",
    talkToRealtor_2: "AGENT: Keep the inspection report and financing dates handy.",
    talkToRealtor_3: "AGENT: I've got your search plan. Meet me at the car outside and we'll tour a few homes.",
    continueRealtorDialogue_1: "AGENT: That gives me a good starting point. Give me a moment to put together our tour.",
    prepareHomeSearch_1: "BZZZ... BEEP! The tour list is ready.",
    returnAgentToDesk_1: "AGENT: I've got your search plan and a list of homes. Meet me outside and we'll start touring.",
  },
  showings: {
    deployAgentToCar_1: "AGENT: Ready to tour homes? I'll be right here by the car.",
    askTourReady_1: "AGENT: Meet me inside. We'll go through your favorite home together.",
    askTourReady_2: "AGENT: You're under contract! Visit the loan officer with the accepted offer.",
    askTourReady_3: "AGENT: Give me a second to bring the car around.",
    confirmTourReady_1: "ME: One more minute. I want to look around first.",
    boardShowingCar_1: "AGENT: Let's inspect the home before we head to the next stop.",
    driveToShowing_1: "ME: Three tours in one day. My feet need their own preapproval.",
    driveToShowing_2: "ME: That was a drive. I'd better try the commute on a workday.",
    driveToShowing_3: "AGENT: First stop. Walk through the door and take a look around.",
    inspectShowingClue_1: "AGENT: Meet me outside and we'll continue the home search.",
    talkShowingAgent_1: "AGENT: Take a look inside. Check the room and talk to me in there.",
  },
  offer: {
    startOfferReview_1: "AGENT: Let's sit back down and talk through the home you picked.",
    confirmOfferDecision_1: "AGENT: I'll tell the seller that date works for you.",
    confirmOfferDecision_2: "AGENT: I'll ask to keep our original closing date.",
    confirmOfferDecision_3: "AGENT: Good news. The seller agreed to our date.",
    confirmOfferDecision_4: "LO: I'll check this home's taxes, insurance, and any HOA dues.",
    confirmOfferDecision_5: "LO: We'll review the full payment and cash to close.",
    confirmOfferDecision_6: "AGENT: Good. Let's review the draft before I send it.",
    confirmOfferDecision_7: "LO: I'll check whether appraisal and loan work fit that date.",
    confirmOfferDecision_8: "AGENT: We found a workable date. Let's decide how to respond.",
  },
  closing: {
    reviewInspection_1: "AGENT: Send the signed contract to your LO. Next comes underwriting.",
    talkUnderwriting_1: "LO: Congrats on the accepted offer. Send me the signed contract.",
    talkUnderwriting_2: "LO: Underwriting has sent a request. Let me print it so we can review what they need.",
    talkUnderwriting_3: "LO: Take the underwriter's request from the printer.",
    talkUnderwriting_4: "LO: The computer at home can help with the deposit trail and insurance quote.",
    talkUnderwriting_5: "LO: Got the deposit explanation and insurance quote. I'll send both for review.",
    talkUnderwriting_6: "LO: The appraisal report is here too. Take a look at the printer.",
    talkUnderwriting_7: "LO: The appraisal report is waiting at the printer.",
    talkUnderwriting_8: "LO: The report supports the agreed price in this story.",
    talkUnderwriting_9: "LO: The underwriter cleared the requested items. We're clear to close!",
    talkUnderwriting_10: "LO: Review your Closing Disclosure before closing day.",
    talkUnderwriting_11: "LO: Your Closing Disclosure is at the printer. Let's review the final figures.",
    talkUnderwriting_12: "LO: The review period has passed. Meet me at the closing office. Your agent will be there too.",
    readUnderwritingRequest_1: "ME: Back to the apartment computer. At least this quest has fewer browser tabs.",
    chooseConditionItem_1: "That's both requested items. Back to the loan officer.",
    readClosingDisclosure_1: "LO: Meet me at the closing office east of the city. Your agent will be there too.",
    enterClosingRoom_1: "AGENT: There you are! From house hunting to closing day. Come on in; we're almost at the finish line.",
    reviewClosingDay_1: "CLOSING HOST: Signed and funded. Here are the keys!",
    reviewClosingDay_2: "LO: Congratulations! It was a pleasure helping you get here.",
    reviewClosingDay_3: "AGENT: Welcome home! Let's get a picture with everyone.",
    reviewClosingDay_4: "ME: We did it!",
  },
};

// Remaining story content, page lists, interactions, objectives and UI copy.
// Functions format dynamic values; preserve their parameters and interpolation.
// Existing LINES keys above remain valid for compatibility with r6.
const SCRIPT = {
  core: {
    buildUI_text_1: "OBJECTIVE:  Explore the apartment",
    buildUI_text_2: "LOAN FILE",
    buildUI_text_3: "INTERACT [E / !]",
    buildUI_text_4: "🙂",
    buildUI_text_5: "NOTICE OF RENT INCREASE",
    buildUI_text_6: "Current Rent:  $1,250\n\nNew Rent:      $1,475\n\nEffective:     NEXT MONTH",
    buildUI_text_7: "E / !  CONTINUE",
    buildUI_text_8: "CLEAR TO CLOSE",
    buildUI_text_9: "AN 8-BIT HOMEBUYING ADVENTURE",
    buildUI_text_10: "PRESS START",
    buildUI_text_11: "QUEST COMPLETE!",
    buildUI_text_12: "BUILD YOUR LOAN FILE\n\nNEXT: FINANCIAL REVIEW",
    buildUI_text_13: "E / !  CONTINUE",
    buildUI_text_14: "E / !  CONTINUE",
    buildUI_reviewPages: [
      ["FINANCIAL REVIEW","LO: Let's look at your income, savings, and monthly payments together. These documents give us a starting point, not a final loan decision."],
      ["BANK STATEMENT","MONDAY:  TACO EMERGENCY       -$18.42\nTUESDAY:  PREMIUM DOG HATS    -$39.99\nWEDNESDAY:  BEANS OF THE MONTH -$24.00"],
      ["ONE BIG DEPOSIT","LO: There's a $4,000 deposit here. What was that from?\n\nPLAYER: My aunt sent it to help with the house. I can ask her for the details.\n\nLO: Great. Let's document where it came from before we count it toward your funds."],
      ["A REALISTIC START","LO: We can work through your budget and possible loan options next. We'll verify the details as we go.\n\nPLAYER: So... the dog hats aren't an automatic no?\n\nLO: Let's just call them a conversation starter."]
    ],
    buildUI_text_15: "YOUR HOME BUDGET",
    buildUI_text_16: "LO: A possible approval ceiling isn't\nyour shopping target. What feels right?",
    buildUI_text_17: "A  Shop at the highest possible amount",
    buildUI_text_18: "B  Set a comfortable monthly budget",
    buildUI_text_19: "UP/DOWN + E  OR TAP AN ANSWER",
    action_text_1: "OBJECTIVE:  Talk to the loan officer for review",
    action_text_2: "LO: Let's start with a payment that fits YOUR life.",
    action_text_3: "OBJECTIVE:  Meet the agent at the car",
    travel_text_1: "OBJECTIVE:  Talk to the loan officer",
    travel_text_2: "OBJECTIVE:  Review the whiteboard",
    travel_text_3: "OBJECTIVE:  Pick up your checklist",
    travel_text_4: "OBJECTIVE:  Give the file to the loan officer",
    travel_text_5: "OBJECTIVE:  Return home for documents",
    travel_text_6: "OBJECTIVE:  Talk to the loan officer for review",
    travel_text_7: "OBJECTIVE:  Discuss loan options",
    travel_text_8: "OBJECTIVE:  Collect the preapproval letter",
    travel_text_9: "OBJECTIVE:  Find a real estate agent",
    travel_text_10: "OBJECTIVE:  Return for financial review",
    travel_text_11: "OBJECTIVE:  Discuss loan options",
    travel_text_12: "OBJECTIVE:  Collect the preapproval letter",
    travel_text_13: "OBJECTIVE:  Walk to the mortgage broker",
  },
  apartment: {
    buildApartment_text_1: "Maintenance request submitted 23 days ago.",
    buildApartment_text_2: "Broken. Again.\nLandlord says he'll send somebody.",
    buildApartment_text_3: "At least the parking lot has a nice view of the other parking lot.",
    buildApartment_text_4: "Maybe later.",
    buildApartment_text_5: "Can't wait for GTA-VI!",
    buildApartment_text_6: "Can't wait for GTA-VI!",
    buildApartment_text_7: "Me and the bike.\nGood times.",
    buildApartment_text_8: "Nothing out there but the hallway and disappointment.",
    buildApartment_text_9: "A document for the loan file.",
    buildInternet_text_1: "PIXELSEARCH",
    buildInternet_text_2: "HOW DO I BUY A HOUSE?",
    buildInternet_text_3: "SEARCH RESULTS",
    buildInternet_text_4: "E / !  READ RESULT",
    buildInternet_text_5: "CONFUSION",
    buildInternet_text_6: "0%",
    buildInternet_text_7: "🙂",
    buildInternet_text_8: "COUSIN DAVE",
    buildInternet_text_9: "bro don't use a Realtor\n\nmy buddy bought a foreclosure\nin 2009\n\ni'll show you how",
    buildInternet_text_10: "E / !  CLOSE",
    buildInternet_text_11: "BUZZ!  BUZZ!",
    buildInternet_text_12: "INCOMING MESSAGE — COUSIN DAVE",
    buildInternet_text_13: "E / !  READ MESSAGE",
    buildInternet_text_14: "CONFUSION: 100%",
    buildInternet_text_15: "INFORMATION OVERLOAD!",
    buildInternet_terms: ["FHA","CONVENTIONAL","USDA","PMI","DTI","ESCROW","DPA",
      "POINTS","LTV","APR","CREDIT SCORE"],
    rentEvent_text_1: "KNOCK!\nKNOCK!\nKNOCK!",
    rentEvent_text_2: "A rent notice.",
    rentEvent_text_3: "OBJECTIVE:  Pick up the letter",
    beginScene2_text_1: "Search the internet.",
    beginScene2_text_2: "OBJECTIVE:  Figure out how to buy a house",
    searchResults: [
      {
        title:"YOU NEED 20% DOWN TO BUY A HOUSE!",
        body:"Every buyer needs a giant down payment. No exceptions!",
        reaction:"I don't have that...",
        confusion:30
      },
      {
        title:"NEVER LET A LENDER PULL YOUR CREDIT!",
        body:"It'll DESTROY your score! Avoid it at all costs!",
        reaction:"Wait... then how do they approve me?",
        confusion:55
      },
      {
        title:"BUY A HOUSE WITH $0 OUT OF POCKET!!!",
        body:"SECRET METHOD lenders DON'T want you to know!",
        reaction:"That seems... suspicious.",
        confusion:80
      },
      {
        title:"FIRST-TIME BUYER GUIDE",
        body:"FHA? CONVENTIONAL? USDA? DPA? PMI? DTI? ESCROW? POINTS?",
        reaction:"...what?",
        confusion:95
      }
    ],
    renderSearch_text_1: "E / !  READ RESULT",
    reactToSearchResult_text_1: "\n\n[E / !]",
    finishInternet_text_1: "E / !  CONTINUE",
    finishInternetAtHome_text_1: "OBJECTIVE:  Walk to the mortgage broker",
  },
  loan_office: {
    buildOffice_text_1: "YOUR LOAN FILE",
    buildOffice_text_2: "INCOME       ASSETS\nCREDIT       DEBTS",
    buildOffice_text_3: "ASSISTANT",
    buildOffice_text_4: "LOAN OFFICER",
    buildOffice_text_5: "EXIT",
    buildOffice_text_6: "Ask the loan officer about your next step.",
    buildOffice_text_7: "Four things we'll look at: income, assets, credit, and debts.",
    buildOffice_text_8: "That printer sounds expensive to fix.",
    buildOffice_text_9: "Head back to town.",
    buildOffice_text_10: "E / !  NEXT",
    buildOffice_loanPages: [
      ["INCOME","How much comes in, and how reliably?\nStart with pay stubs and your W-2."],
      ["ASSETS","What money is available for the purchase?\nBring recent bank statements."],
      ["CREDIT","Your credit history helps shape loan options.\nWe'll review it together."],
      ["DEBTS","Monthly payments affect your budget.\nWe'll look at the whole picture."]
    ],
    talkToOfficer_text_1: "OBJECTIVE:  Review the whiteboard",
    startLoanOptions_text_1: "UP/DOWN + E  OR TAP AN ANSWER",
    collectPreapproval_text_1: "OBJECTIVE:  Find a real estate agent",
    siftQualificationPapers_text_1: "ONE MOMENT...",
    siftQualificationPapers_text_2: (page) => `REVIEWING FILE  ${page}/3`,
    printPreapprovalCinematic_text_1: "PREAPPROVAL LETTER",
    printPreapprovalCinematic_text_2: "OBJECTIVE:  Collect the preapproval letter",
    printPreapprovalCinematic_text_3: "BRRZZT... BEEP!  The letter is ready.",
    printStoryDocument_text_1: (documentName) => `BRRZZT...  ${documentName}`,
    collectReviewedDocuments_text_1: "🙂",
    collectReviewedDocuments_text_2: "😳",
    updateDocumentObjective_text_1: (checkmark) => `${checkmark} Pay stubs`,
    updateDocumentObjective_text_2: (checkmark) => `${checkmark} W-2`,
    updateDocumentObjective_text_3: (checkmark) => `${checkmark} Photo ID`,
    updateDocumentObjective_text_4: (checkmark) => `${checkmark} Full statement`,
    updateDocumentObjective_text_5: "OBJECTIVE:  Return to the loan officer",
    updateDocumentObjective_text_6: (count) => `OBJECTIVE:  Find documents (${count}/4)`,
    collectDocument_lines: {
      paystub:"Pay stubs! I knew that drawer had something useful.",
      w2:"Found the W-2 in the filing cabinet.",
      id:"My photo ID was in the wallet. A rare easy win.",
      statement:"Downloaded the entire bank statement. Every page."
    },
    nextLoanPage_text_1: "OBJECTIVE:  Pick up your checklist",
    printChecklistCinematic_text_1: "DOCUMENT CHECKLIST",
    printChecklistCinematic_text_2: "OBJECTIVE:  Pick up your checklist",
    printChecklistCinematic_text_3: "BRRZZT... BEEP!  The checklist is ready.",
    printChecklist_text_1: "OBJECTIVE:  Return home for documents",
  },
  town: {
    buildTown_text_1: "APARTMENT",
    buildTown_text_2: "MORTGAGE BROKER",
    buildTown_text_3: "AGENT →",
    buildTown_text_4: "Go inside the apartment.",
    buildTown_text_5: "Go inside the mortgage broker's office.",
    buildTown_text_6: "A nice bench for my two-minute commute.",
    buildDowntown_text_1: "DISCOUNT REALTY",
    buildDowntown_text_2: "COUSIN DAVE",
    buildDowntown_text_3: "kw",
    buildDowntown_text_4: "KELLER WILLIAMS",
    buildDowntown_text_5: "AGENT",
    buildDowntown_text_6: "← BROKER",
    buildDowntown_text_7: "DISCOUNT REALTY: 'Why pay full price for advice?'\n...I think I'll keep looking.",
    buildDowntown_text_8: "Talk with Cousin Dave.",
    buildDowntown_text_9: "Nice car. Looks like somebody spends a lot of time driving to showings.",
    buildDowntown_text_10: "Talk with the agent.",
    showTown_text_1: "OBJECTIVE:  Find a real estate agent",
    showTown_text_2: "OBJECTIVE:  Return for financial review",
    showTown_text_3: "OBJECTIVE:  Discuss loan options",
    showTown_text_4: "OBJECTIVE:  Collect the preapproval letter",
    showTown_text_5: "OBJECTIVE:  Return to the loan officer",
    showTown_text_6: "OBJECTIVE:  Walk home for documents",
    showTown_text_7: "OBJECTIVE:  Walk to the mortgage broker",
    showDowntown_text_1: "OBJECTIVE:  Find a real estate agent",
  },
  realtor_office: {
    buildRealtorOffice_text_1: "kw",
    buildRealtorOffice_text_2: "KELLER WILLIAMS",
    buildRealtorOffice_text_3: "REAL ESTATE AGENT",
    buildRealtorOffice_text_4: "MLS",
    buildRealtorOffice_text_5: "EXIT",
    buildRealtorOffice_text_6: "Talk with the real estate agent.",
    buildRealtorOffice_text_7: "Sit down with the agent.",
    buildRealtorOffice_text_8: "E / !  CONTINUE",
    buildRealtorOffice_realtorPages: [
      ["BUYER CONSULTATION","AGENT: Before we chase listings, let's figure out what actually fits your life."],
      ["WHERE + WHAT","We'll narrow the area, property type, bedrooms, garage, yard, and the things you refuse to compromise on."],
      ["YOUR REAL BUDGET","AGENT: We'll shop around the comfortable target you worked out with your loan officer — not just the biggest number on the letter."],
      ["THE WHOLE PAYMENT","Taxes, homeowners insurance, HOA dues, and maintenance can change the monthly picture. We'll keep those in view too."],
      ["SEARCH PLAN","AGENT: Perfect. I'll build a short list instead of sending you 147 random houses and calling it a strategy."],
      ["CONSULTATION COMPLETE ✓","KELLER WILLIAMS\n\nLocal expertise. Education first.\n\nNext up: house hunting."]
    ],
    buildRealtorOffice_text_9: "HOME BUYING TEAM",
    buildRealtorOffice_text_10: "LO: Looks like you've got your team.\n\nAGENT: I've already got a few houses in mind.\n\nME: Let's go.\n\n          ★ DREAM TEAM UNLOCKED ★",
    buildRealtorOffice_text_11: "E / !  CONTINUE",
    enterRealtorOffice_text_1: "OBJECTIVE:  Review the home with the agent",
    enterRealtorOffice_text_2: "OBJECTIVE:  Meet the agent at the car",
    enterRealtorOffice_text_3: "OBJECTIVE:  Talk to the agent about your pick",
    enterRealtorOffice_text_4: "OBJECTIVE:  Meet the agent at the car",
    enterRealtorOffice_text_5: "OBJECTIVE:  Talk to the real estate agent",
    enterRealtorOffice_text_6: "OBJECTIVE:  Sit down with the agent",
    continueRealtorDialogue_lines: [
      "AGENT: Before we chase listings, let's figure out what fits your life.",
      "AGENT: What area, property type, bedrooms, garage, and yard do you want? What won't you compromise on?",
      "AGENT: We'll shop around the comfortable target you worked out with your loan officer.",
      "AGENT: Taxes, insurance, HOA dues, and maintenance affect the full monthly payment.",
      "AGENT: I'll build a short list instead of sending you 147 random houses."
    ],
    prepareHomeSearch_text_1: "SEARCH",
    prepareHomeSearch_text_2: "FILTER",
    prepareHomeSearch_text_3: "MATCH!",
    prepareHomeSearch_text_4: "3 HOMES",
    prepareHomeSearch_text_5: "BZZZ...  HOMES TO TOUR",
  },
  showings: {
    buildHouseHunting_showingHouses: [
      {name:"THE CHARMER",summary:"Great kitchen. Ask about the older roof.",
        feature:"ME: This kitchen feels like home. Sunday pancakes, definitely.",
        agent:"AGENT: Let's read the disclosures together and make sure you have no questions about that older roof."},
      {name:"EASY LIVING",summary:"Low upkeep. Check HOA dues and rules.",
        feature:"ME: Less space to clean. My vacuum just applauded.",
        agent:"AGENT: Let's check the condo rules and HOA payments together, so you know the full monthly cost."},
      {name:"THE RANCH",summary:"Big yard. Test the longer commute.",
        feature:"ME: A yard! I could grow one heroic tomato out there.",
        agent:"AGENT: Let's try this commute on a workday and decide how the extra drive feels."}
    ],
    buildHouseHunting_text_1: "CONDOS",
    buildHouseHunting_text_2: "AGENT",
    buildHouseHunting_text_3: "AGENT",
    buildHouseHunting_text_4: "EXIT",
    buildHouseHunting_text_5: "AGENT: READY TO TOUR HOMES?",
    buildHouseHunting_text_6: "LET'S GO",
    buildHouseHunting_text_7: "GIVE ME A MINUTE",
    buildHouseHunting_text_8: "UP/DOWN + E  OR TAP",
    buildHouseHunting_text_9: "WHICH ONE MAKES THE SHORTLIST?",
    buildHouseHunting_text_10: (number, homeName, summary) => `${number}. ${homeName}\n   ${summary}`,
    buildHouseHunting_text_11: "UP/DOWN + E  OR TAP A HOME",
    askTourReady_text_1: (homeName) => `AGENT: Let's review ${homeName} inside before we write an offer.`,
    setDriveLandmarks_text_1: "TBD CORP",
    setDriveLandmarks_text_2: "FREE COFFEE?\nASK HR",
    setDriveLandmarks_text_3: "DOG\nPARK",
    setDriveLandmarks_text_4: "OPEN HOUSE\nSNAKE? NO.",
    setDriveLandmarks_text_5: "CONDOS",
    setDriveLandmarks_text_6: "HOA: PLEASE\nNO GNOMES",
    setDriveLandmarks_text_7: "FURTHER\nTHAN IT LOOKS",
    setDriveLandmarks_text_8: "MOO",
    setDriveLandmarks_text_9: "ARE WE\nTHERE YET?",
    setDriveLandmarks_text_10: "BACK TO\nTOWN",
    setDriveLandmarks_text_11: "ALMOST\nTHERE",
    driveToShowing_text_1: "HEADING BACK",
    driveToShowing_text_2: (homeNumber) => `ON THE WAY TO HOME ${homeNumber}`,
    showShowingStreet_text_1: "OBJECTIVE:  Return to town or revisit",
    showShowingStreet_text_2: "OBJECTIVE:  Compare homes with the agent",
    showShowingStreet_text_3: "OBJECTIVE:  Board the car for the next home",
    showShowingStreet_text_4: "OBJECTIVE:  Walk into the home and explore",
    enterShowingHome_text_1: "OBJECTIVE:  Tour the home with the agent",
    arriveShowingHome_text_1: "OBJECTIVE:  Explore or meet the agent outside",
    arriveShowingHome_text_2: "OBJECTIVE:  Inspect the room and talk to the agent",
    arriveShowingHome_invitations: [
        "AGENT: Welcome to the Charmer. Have a look around, then come tell me what you think.",
        "AGENT: Make yourself at home. Explore the rooms and check the condo information while we're here.",
        "AGENT: Take your time with this one. Look around and picture an ordinary day living here."
      ],
    leadShowingAgentOutside_text_1: "OBJECTIVE:  Follow the agent outside",
    inspectShowingClue_text_1: "OBJECTIVE:  Meet the agent outside",
    talkShowingAgent_text_1: (homeName) => `AGENT: ${homeName} is shortlisted. Ready to head back?`,
    talkShowingAgent_text_2: "AGENT: Well, what did you think? One more home to go! Ready when you are.",
    talkShowingAgent_text_3: "AGENT: Well, what did you think? The car is ready when you are.",
    chooseShowingFavorite_text_1: "OBJECTIVE:  Board the car to return to town",
    chooseShowingFavorite_text_2: (homeName) => `AGENT: ${homeName} is shortlisted. We'll verify payment and condition before an offer.`,
  },
  offer: {
    buildOfferScene_text_1: "E / !  CONTINUE",
    buildOfferScene_text_2: "UP/DOWN + E  OR TAP",
    guideOfferAgentInside_text_1: "OBJECTIVE:  Meet the agent inside",
    startOfferReview_concerns: [
      "AGENT: Let's read the disclosures and ask about the older roof. An inspection can tell us more about its condition.",
      "AGENT: Let's read the condo rules and review the HOA dues and any assessments. The monthly cost has to work for you.",
      "AGENT: The yard is tempting. Let's also think through that longer workday commute and what an inspection may find."
    ],
    startOfferReview_pages: (homeName, concern) => [
      [homeName,concern],
      ["THE FULL PAYMENT",
        "AGENT: The loan letter is a starting point. Ask the LO for a home-specific estimate: loan payment, taxes, insurance, any mortgage insurance, HOA dues, and cash to close."],
      ["WHAT GOES IN AN OFFER",
        "AGENT: We'll discuss price using recent sales, earnest money, deadlines, and inspection, financing, and appraisal terms. Read the proposed contract before signing."]
    ],
    startOfferReview_text_1: "ME: I like it. What should we check before making an offer?",
    startOfferReview_text_2: "AGENT: Ask your LO for this home's full payment: taxes, insurance, mortgage insurance, and any HOA dues.",
    startOfferReview_text_3: "AGENT: We'll also confirm cash to close, price, earnest money, deadlines, and the contract protections.",
    startOfferReview_text_4: "AGENT: Read the proposed contract and ask questions before signing.",
    renderOfferView_text_1: (page, total) => `  ${page}/${total}`,
    renderOfferView_text_2: "E / !  CONTINUE",
    renderOfferView_text_3: "REVIEW YOUR OFFER",
    renderOfferView_text_4: (homeName) => `${homeName}\n\nPrice: discuss recent sales and budget.\nEarnest money and deadlines: read the contract.\nInspection, financing, and appraisal terms: review with the agent.\nClosing date: confirm with the LO.`,
    renderOfferView_text_5: "E / !  SEND OFFER",
    renderOfferView_text_6: "OFFER SENT",
    renderOfferView_text_7: (homeName) => `Your agent submitted the offer on ${homeName}. Now we wait for the seller's response.\n\nME: I am being extremely normal about this.`,
    renderOfferView_text_8: "E / !  CHECK REPLY",
    renderOfferView_text_9: "OFFER ACCEPTED!",
    renderOfferView_text_10: (closingResult) => `${closingResult} You're under contract.\n\nNext: inspection, appraisal, and loan underwriting. There is still work to do before closing.`,
    renderOfferView_text_11: "E / !  CONTINUE",
    advanceOfferView_text_1: "OBJECTIVE:  Ask the agent about inspection",
    showOfferDecision_text_1: "BEFORE WE SEND IT",
    showOfferDecision_text_2: "AGENT: Let's verify this home's payment and cash to close. A preapproval letter doesn't include every detail of a particular home.",
    showOfferDecision_text_3: "CALL THE LO ABOUT THIS HOME",
    showOfferDecision_text_4: "THE LETTER IS CLOSE ENOUGH",
    showOfferDecision_text_5: "SELLER COUNTEROFFER",
    showOfferDecision_text_6: "AGENT: The seller wants an earlier closing date. Let's check whether our financing timeline can support it.",
    showOfferDecision_text_7: "CHECK THE TIMELINE WITH THE LO",
    showOfferDecision_text_8: "SURE, HOW ABOUT TOMORROW?",
    showOfferDecision_text_9: "YOUR RESPONSE",
    showOfferDecision_text_10: "AGENT: We checked the loan timeline. The seller offered a workable date. How would you like me to respond?",
    showOfferDecision_text_11: "ACCEPT THE WORKABLE DATE",
    showOfferDecision_text_12: "ASK FOR OUR ORIGINAL DATE",
    showOfferDecision_text_13: "UP/DOWN + E  OR TAP",
    confirmOfferDecision_text_1: "AGENT: LET'S GET THE HOME-SPECIFIC NUMBERS.",
    confirmOfferDecision_text_2: "AGENT: WE NEED A WORKABLE DATE FIRST.",
    confirmOfferDecision_text_3: "The seller accepted the date you confirmed with the LO.",
    confirmOfferDecision_text_4: "The seller agreed to keep your original closing date.",
    confirmOfferDecision_text_5: "AGENT: Here's the draft: price, deposit, deadlines, closing date, and inspection and financing terms.",
    confirmOfferDecision_text_6: "ME: We've gone through it and my questions are answered. Let's send it.",
    confirmOfferDecision_text_7: "AGENT: Offer submitted. Now we wait for the seller.",
    confirmOfferDecision_text_8: "ME: I am being extremely normal about this.",
    showOfferAccepted_text_1: "AGENT: The seller accepted! We're under contract.",
    showOfferAccepted_text_2: "ME: So there's still the inspection and loan work before closing?",
    showOfferAccepted_text_3: "AGENT: Exactly. Let's talk about the inspection next.",
  },
  closing: {
    buildFinalChapters_text_1: "E / !  CONTINUE",
    buildFinalChapters_text_2: "THE FOLLOW-UP FILE",
    buildFinalChapters_text_3: "Choose an item to collect:",
    buildFinalChapters_text_4: "UP/DOWN + E  OR TAP",
    buildFinalChapters_text_5: "CLEAR TO CLOSE!",
    buildFinalChapters_text_6: "CLOSING →",
    buildFinalChapters_text_7: "CLOSING OFFICE",
    buildFinalChapters_text_8: "← AGENT",
    buildFinalChapters_text_9: "CLOSING HOST",
    buildFinalChapters_text_10: "AGENT",
    buildFinalChapters_text_11: "LOAN OFFICER",
    buildFinalChapters_text_12: "EXIT",
    buildFinalChapters_text_13: "KEYS IN HAND!",
    buildFinalChapters_text_14: "CLEAR TO CLOSE!",
    buildFinalChapters_text_15: "HOMEOWNER!",
    buildFinalChapters_text_16: "E / !  PLAY AGAIN",
    lateQuestObjective_text_1: "OBJECTIVE:  Enter the closing office",
    lateQuestObjective_text_2: "OBJECTIVE:  Review and sign the papers",
    lateQuestObjective_text_3: "OBJECTIVE:  Go to the closing office",
    lateQuestObjective_text_4: "OBJECTIVE:  Review Closing Disclosure",
    lateQuestObjective_text_5: "OBJECTIVE:  Return to the loan officer",
    lateQuestObjective_text_6: "OBJECTIVE:  Discuss appraisal with LO",
    lateQuestObjective_text_7: "OBJECTIVE:  Return to the loan officer",
    lateQuestObjective_text_8: "OBJECTIVE:  Read the appraisal report",
    lateQuestObjective_text_9: "OBJECTIVE:  Return to the loan officer",
    lateQuestObjective_text_10: "OBJECTIVE:  Bring requested items to LO",
    lateQuestObjective_text_11: (count) => `OBJECTIVE:  Collect follow-up items (${count}/2)`,
    lateQuestObjective_text_12: "OBJECTIVE:  Go home for requested items",
    lateQuestObjective_text_13: "OBJECTIVE:  Read underwriter request",
    lateQuestObjective_text_14: "OBJECTIVE:  Return to the loan officer",
    lateQuestObjective_text_15: "OBJECTIVE:  Ask the agent about inspection",
    lateQuestObjective_text_16: "OBJECTIVE:  Return to the agent for inspection",
    lateQuestObjective_text_17: "OBJECTIVE:  Talk to the loan officer",
    lateQuestObjective_text_18: "OBJECTIVE:  Meet the agent inside",
    lateQuestObjective_text_19: "OBJECTIVE:  Talk to the agent about your pick",
    lateQuestObjective_text_20: "OBJECTIVE:  Meet the agent at the car",
    showStoryCards_text_1: "E / !  CONTINUE",
    renderStoryCard_text_1: (heading, page, total) => `${heading}  ${page}/${total}`,
    renderStoryCard_text_2: "E / !  CONTINUE",
    reviewInspection_notes: [
      "AGENT: We read the inspector's notes on the older roof and asked our questions. We understand the condition and choose to move forward.",
      "AGENT: We checked the condo's condition and the documents about its rules and costs. We know what to ask before proceeding.",
      "AGENT: We checked the ranch's condition. The commute is still longer, but you tested it and decided it works for you."
    ],
    reviewInspection_pages: (homeName, note) => [
      ["HOME INSPECTION", "An independent inspector examines the home's condition for you. The lender's appraisal, which comes later, focuses on value."],
      [homeName, note]
    ],
    reviewInspection_text_1: "E / !  CONTINUE",
    talkUnderwriting_text_1: "UNDERWRITER'S REQUEST",
    talkUnderwriting_text_2: "BZZZ... BEEP! The underwriter's request is ready.",
    talkUnderwriting_text_3: "APPRAISAL REPORT",
    talkUnderwriting_text_4: "CLOSING DISCLOSURE",
    readUnderwritingRequest_pages: [
      ["UNDERWRITING", "The underwriter verifies the information in the loan file. A follow-up request is common; it is a request for documents, not a final loan decision."],
      ["DEPOSIT TRAIL", "The $4,000 from Aunt needs a written explanation and any records the lender requests about where it came from."],
      ["HOME INSURANCE", "The file also needs insurance details for the home you chose. Check coverage and cost before you send a quote."]
    ],
    readUnderwritingRequest_text_1: "E / !  TAKE REQUEST",
    showConditionMenu_text_1: "UP/DOWN + E  OR TAP",
    renderConditionMenu_text_1: (checkmark) => `${checkmark}  DEPOSIT EXPLANATION FROM AUNT`,
    renderConditionMenu_text_2: (checkmark) => `${checkmark}  HOME INSURANCE QUOTE`,
    renderConditionMenu_text_3: "LEAVE COMPUTER",
    chooseConditionItem_text_1: "ALREADY SAVED. CHOOSE ANOTHER ITEM.",
    chooseConditionItem_text_2: "AUNT: I sent the deposit details. Please retire the dog-hat subscription.",
    chooseConditionItem_text_3: "ME: Insurance quote saved. That belongs in the full housing budget too.",
    readAppraisal_pages: [
      ["APPRAISAL REPORT", "An independent appraiser gives an opinion of the home's value for the lender. That is different from a buyer's home inspection."],
      ["THIS HOME", "The report supports the agreed price in this story. If it had come in low, we'd talk with the agent and LO about the options before deciding what to do."]
    ],
    readAppraisal_text_1: "E / !  FILE REPORT",
    readClosingDisclosure_pages: [
      ["CLOSING DISCLOSURE", "The lender provides this at least three business days before closing, giving you time to review the final loan terms and costs."],
      ["COMPARE + ASK", "Compare the payment, closing costs, and cash to close with your Loan Estimate. Ask about anything you don't understand or that changed."],
      ["THREE BUSINESS DAYS LATER", "ME: I asked my questions, checked the numbers, and finally understand what cash to close means. Closing day is here."]
    ],
    readClosingDisclosure_text_1: "E / !  FINISH REVIEW",
    reviewClosingDay_pages: [
      ["FINAL WALK-THROUGH", "AGENT: We checked the home and the agreed items before closing. If anything differs from the contract, we ask before signing."],
      ["THE LAST CHECK", "CLOSING HOST: Take your time. Compare the documents with the Closing Disclosure you reviewed, and ask if a term or cost is unclear."],
      ["READY TO SIGN?", "ME: The numbers match what I reviewed, and my questions are answered. All right... where's the pen?"]
    ],
    reviewClosingDay_text_1: "E / !  SIGN & FINISH",
    showHomeownerScreen_text_1: (homeName) => `WELCOME TO ${homeName}`,
  },
};
